# The URL the site will be built for
base_url = "https://vsf4h-pyaaa-aaaah-ara3q-cai.icp0.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Define the taxonomies
taxonomies = [
    {name = "doctrines"},
    {name = "authors"}
]

[extra]
# Additional site configuration
theme = "zolastrap"
