name: Deploy to Internet Computer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DFX_VERSION: 0.24.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Zola
        run: |
          sudo snap install --edge zola

      - name: Build site
        run: zola build

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "${{ env.DFX_VERSION }}"

      - name: Configure dfx identity
        env:
          IC_DEPLOY_KEY: ${{ secrets.IC_DEPLOY_KEY }}
        run: |
          mkdir -p ./tmp/identity/ci
          echo "$IC_DEPLOY_KEY" > ./tmp/identity/ci/identity.pem
          dfx identity import ci ./tmp/identity/ci/identity.pem --storage-mode=plaintext

      - name: Initialize dfx
        run: |
          dfx identity use ci

      - name: Deploy to IC
        run: |
          dfx deploy --network ic 
